#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# run_weighting_retest.sh — PERIODIC RE-TEST of the UpJump companion ladder
# weighting + coin-extension backtests (S-2026-07-08, task 3).
#
# Re-runnable + idempotent: rebuilds the canonical harness from source, gates
# every input file, re-runs the full metric suite on CURRENT local data and
# writes a dated report to outputs/CRYPTO_WEIGHTING_RETEST_<YYYY-MM-DD>.md
# (same-day rerun overwrites the same file). NEVER touches live processes,
# crontabs, or the ChimeraCrypto working tree.
#
# What it re-answers monthly:
#   • is the x2/x1 split still right? (live per-coin honest all-6 + random ctl)
#   • does any live book go BT-net-negative? (-> rank-out candidate, flag loudly)
#   • do the retirement thresholds (-2x BT maxDD) need re-derivation?
#   • do AAVE/OP (or any new *_1h.csv coin) now clear the extension bar?
#
# Requires: sibling checkout of ChimeraCrypto (the live engine header) at
# ../../ChimeraCrypto relative to backtest/ — same dependency as validate_ladder.cpp.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BT="$REPO/backtest"
OUT="$REPO/outputs"
HDR_DIR="$REPO/../ChimeraCrypto/include"
DATE="$(date +%Y-%m-%d)"
REPORT="$OUT/CRYPTO_WEIGHTING_RETEST_${DATE}.md"
LIVE_COINS="BTC ETH SOL DOGE BNB ADA TRX NEAR"

[ -d "$HDR_DIR/core" ] || { echo "FATAL: ChimeraCrypto checkout not found at $HDR_DIR (live engine header needed)"; exit 1; }
mkdir -p "$OUT"
cd "$BT"

# 1) data integrity gate — a REJECTED file aborts the whole re-test (fail-closed).
echo "[RETEST] integrity gate..."
for c in $LIVE_COINS AAVE OP; do
    [ -f "data/${c}USDT_1h.csv" ] || { echo "FATAL: missing data/${c}USDT_1h.csv"; exit 1; }
    python3 integrity_gate.py "data/${c}USDT_1h.csv" >/dev/null 2>&1 \
        || { echo "FATAL: integrity gate REJECTED data/${c}USDT_1h.csv — not used, aborting"; exit 1; }
done

# 2) rebuild the harness from committed source (idempotent).
echo "[RETEST] building harness..."
g++ -O2 -std=c++17 -I"$HDR_DIR" upjump_weighting_bt.cpp -o upjump_weighting_bt

run() { ./upjump_weighting_bt "$@" 2>&1 | grep -v '^\[CLIP\]'; }

# 3) run the suite -> dated report.
echo "[RETEST] running suite..."
{
    echo "# CRYPTO WEIGHTING / EXTENSION RE-TEST — ${DATE}"
    echo
    echo "Auto-generated by tools/run_weighting_retest.sh (monthly cadence)."
    echo "Harness: backtest/upjump_weighting_bt.cpp driving the LIVE UpJumpLadderCompanion.hpp."
    echo "Baseline + decision rules: outputs/CRYPTO_WEIGHTING_RETIREMENT_2026-07-08.md."
    echo "Books judged STANDALONE (never vs riding WIDE). No BE-floors, no DMA gates."
    echo
    echo "## Anchor + parity (must hold before trusting anything below)"
    echo '```'
    run anchor
    echo '```'
    echo
    echo "## Per-coin live config — honest all-6"
    echo "Rank-out rule: any live coin with net% <= 0 here is a RANK-OUT candidate — flag to operator."
    echo "x2 rule: honest all-6 PASS **and** random-control z >= 2.0."
    echo '```'
    run live
    echo '```'
    echo
    echo "## Per-year nets (episode entry-year attribution)"
    echo '```'
    run years
    echo '```'
    echo
    echo "## Random-entry control (bull-beta guard)"
    echo '```'
    run random
    echo '```'
    echo
    echo "## maxDD drift check"
    echo "Retirement thresholds are -2x the maxDDbp column above; if a coin's maxDD has grown"
    echo ">25% past the shipped basis (see the 2026-07-08 report), re-derive and re-wire."
    echo
    echo "## Coin extension (AAVE / OP / any new data/ coin)"
    echo '```'
    run ext AAVE OP
    echo '```'
    echo
    echo "_No wiring is changed by this script. Operator reviews + a session re-wires if the split moved._"
} > "$REPORT"

echo "[RETEST] report written: $REPORT"
